-- =============================================================================
-- AUTO-GENERATED by axi_wrapper -- DO NOT EDIT MANUALLY
-- Source entity : pwm_controller
-- Register width: 32 bits
-- Registers     : 5
--
-- Port direction convention (from the AXI interface perspective):
--   RW / WO fields  -> register drives DUT input -> port is OUT on this entity
--   RO fields       -> DUT output drives register -> port is IN  on this entity
-- =============================================================================
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity axi_lite_if is
  generic (
    C_S_AXI_DATA_WIDTH : integer := 32;
    C_S_AXI_ADDR_WIDTH : integer := 5
  );
  port (
    -- AXI4-Lite clock and reset
    S_AXI_ACLK    : in  std_logic;
    S_AXI_ARESETN : in  std_logic;
    -- Write address channel
    S_AXI_AWADDR  : in  std_logic_vector(C_S_AXI_ADDR_WIDTH-1 downto 0);
    S_AXI_AWPROT  : in  std_logic_vector(2 downto 0);
    S_AXI_AWVALID : in  std_logic;
    S_AXI_AWREADY : out std_logic;
    -- Write data channel
    S_AXI_WDATA   : in  std_logic_vector(C_S_AXI_DATA_WIDTH-1 downto 0);
    S_AXI_WSTRB   : in  std_logic_vector((C_S_AXI_DATA_WIDTH/8)-1 downto 0);
    S_AXI_WVALID  : in  std_logic;
    S_AXI_WREADY  : out std_logic;
    -- Write response channel
    S_AXI_BRESP   : out std_logic_vector(1 downto 0);
    S_AXI_BVALID  : out std_logic;
    S_AXI_BREADY  : in  std_logic;
    -- Read address channel
    S_AXI_ARADDR  : in  std_logic_vector(C_S_AXI_ADDR_WIDTH-1 downto 0);
    S_AXI_ARPROT  : in  std_logic_vector(2 downto 0);
    S_AXI_ARVALID : in  std_logic;
    S_AXI_ARREADY : out std_logic;
    -- Read data channel
    S_AXI_RDATA   : out std_logic_vector(C_S_AXI_DATA_WIDTH-1 downto 0);
    S_AXI_RRESP   : out std_logic_vector(1 downto 0);
    S_AXI_RVALID  : out std_logic;
    S_AXI_RREADY  : in  std_logic;
    -- RW/WO fields: register drives the DUT input port -- OUT on this entity
    enable                        : out std_logic;
    irq_mask                      : out std_logic_vector(3 downto 0);
    duty_cycle                    : out std_logic_vector(7 downto 0);
    prescaler                     : out std_logic_vector(15 downto 0);
    -- RO fields: DUT output port drives the register -- IN on this entity
    pwm_out                       : in  std_logic;
    period_done                   : in  std_logic;
    irq_status                    : in  std_logic_vector(3 downto 0);
    cycle_count                   : in  std_logic_vector(31 downto 0);
    -- Dummy terminator (avoids trailing semicolon issues)
    dummy_unused : in std_logic := '0'
  );
end entity axi_lite_if;

architecture rtl of axi_lite_if is
  -- -------------------------------------------------------------------------
  -- AXI handshake internals
  -- -------------------------------------------------------------------------
  signal axi_awaddr  : std_logic_vector(C_S_AXI_ADDR_WIDTH-1 downto 0);
  signal axi_awready : std_logic;
  signal axi_wready  : std_logic;
  signal axi_bresp   : std_logic_vector(1 downto 0);
  signal axi_bvalid  : std_logic;
  signal axi_araddr  : std_logic_vector(C_S_AXI_ADDR_WIDTH-1 downto 0);
  signal axi_arready : std_logic;
  signal axi_rdata   : std_logic_vector(C_S_AXI_DATA_WIDTH-1 downto 0);
  signal axi_rresp   : std_logic_vector(1 downto 0);
  signal axi_rvalid  : std_logic;
  signal aw_en       : std_logic;
  -- -------------------------------------------------------------------------
  -- Register shadows (one per register in the map)
  -- -------------------------------------------------------------------------
  signal reg_ctrl_reg : std_logic_vector(C_S_AXI_DATA_WIDTH-1 downto 0) := (others => '0');
  signal reg_duty_reg : std_logic_vector(C_S_AXI_DATA_WIDTH-1 downto 0) := (others => '0');
  signal reg_prescaler_reg : std_logic_vector(C_S_AXI_DATA_WIDTH-1 downto 0) := (others => '0');
  signal reg_status_reg : std_logic_vector(C_S_AXI_DATA_WIDTH-1 downto 0) := (others => '0');
  signal reg_cycle_cnt_reg : std_logic_vector(C_S_AXI_DATA_WIDTH-1 downto 0) := (others => '0');
  -- -------------------------------------------------------------------------
  -- Address word decode (drop 2 LSBs for byte to word addressing)
  -- -------------------------------------------------------------------------
  constant ADDR_LSB          : integer := (C_S_AXI_DATA_WIDTH / 32) + 1;
  constant OPT_MEM_ADDR_BITS : integer := C_S_AXI_ADDR_WIDTH - 1 - ADDR_LSB;

begin
  -- =========================================================================
  -- AXI channel output tie-offs
  -- =========================================================================
  S_AXI_AWREADY <= axi_awready;
  S_AXI_WREADY  <= axi_wready;
  S_AXI_BRESP   <= axi_bresp;
  S_AXI_BVALID  <= axi_bvalid;
  S_AXI_ARREADY <= axi_arready;
  S_AXI_RDATA   <= axi_rdata;
  S_AXI_RRESP   <= axi_rresp;
  S_AXI_RVALID  <= axi_rvalid;
  -- =========================================================================
  -- Write address channel: AWREADY / AW_EN
  -- =========================================================================
  p_awready : process(S_AXI_ACLK)
  begin
    if rising_edge(S_AXI_ACLK) then
      if S_AXI_ARESETN = '0' then
        axi_awready <= '0';
        aw_en       <= '1';
      else
        if aw_en = '1' and S_AXI_AWVALID = '1' and S_AXI_WVALID = '1' then
          axi_awready <= '1';
          aw_en       <= '0';
        elsif S_AXI_BREADY = '1' and axi_bvalid = '1' then
          aw_en <= '1';
        else
          axi_awready <= '0';
        end if;
      end if;
    end if;
  end process p_awready;
  p_awaddr : process(S_AXI_ACLK)
  begin
    if rising_edge(S_AXI_ACLK) then
      if S_AXI_ARESETN = '0' then
        axi_awaddr <= (others => '0');
      else
        if aw_en = '1' and S_AXI_AWVALID = '1' and S_AXI_WVALID = '1' then
          axi_awaddr <= S_AXI_AWADDR;
        end if;
      end if;
    end if;
  end process p_awaddr;
  -- =========================================================================
  -- Write data channel: WREADY
  -- =========================================================================
  p_wready : process(S_AXI_ACLK)
  begin
    if rising_edge(S_AXI_ACLK) then
      if S_AXI_ARESETN = '0' then
        axi_wready <= '0';
      else
        if aw_en = '1' and S_AXI_AWVALID = '1' and S_AXI_WVALID = '1' then
          axi_wready <= '1';
        else
          axi_wready <= '0';
        end if;
      end if;
    end if;
  end process p_wready;
  -- =========================================================================
  -- Register write process
  --   CPU write path : AXI write data captured into shadow register
  --   RO capture     : DUT output port value latched into shadow each cycle
  -- =========================================================================
  p_reg_write : process(S_AXI_ACLK)
    variable loc_addr : std_logic_vector(OPT_MEM_ADDR_BITS downto 0);
  begin
    if rising_edge(S_AXI_ACLK) then
      if S_AXI_ARESETN = '0' then
        reg_ctrl_reg <= (others => '0');
        reg_duty_reg <= (others => '0');
        reg_prescaler_reg <= (others => '0');
        reg_status_reg <= (others => '0');
        reg_cycle_cnt_reg <= (others => '0');
      else
        -- CPU write path
        if axi_awready = '1' and S_AXI_AWVALID = '1' and
           axi_wready  = '1' and S_AXI_WVALID  = '1' then
          loc_addr := axi_awaddr(ADDR_LSB + OPT_MEM_ADDR_BITS downto ADDR_LSB);
          case loc_addr is
            when b"000" =>
              if S_AXI_WSTRB(0) = '1' then
                reg_ctrl_reg(7 downto 0) <=
                  S_AXI_WDATA(7 downto 0);
              end if;
              if S_AXI_WSTRB(1) = '1' then
                reg_ctrl_reg(15 downto 8) <=
                  S_AXI_WDATA(15 downto 8);
              end if;
              if S_AXI_WSTRB(2) = '1' then
                reg_ctrl_reg(23 downto 16) <=
                  S_AXI_WDATA(23 downto 16);
              end if;
              if S_AXI_WSTRB(3) = '1' then
                reg_ctrl_reg(31 downto 24) <=
                  S_AXI_WDATA(31 downto 24);
              end if;
            when b"001" =>
              if S_AXI_WSTRB(0) = '1' then
                reg_duty_reg(7 downto 0) <=
                  S_AXI_WDATA(7 downto 0);
              end if;
              if S_AXI_WSTRB(1) = '1' then
                reg_duty_reg(15 downto 8) <=
                  S_AXI_WDATA(15 downto 8);
              end if;
              if S_AXI_WSTRB(2) = '1' then
                reg_duty_reg(23 downto 16) <=
                  S_AXI_WDATA(23 downto 16);
              end if;
              if S_AXI_WSTRB(3) = '1' then
                reg_duty_reg(31 downto 24) <=
                  S_AXI_WDATA(31 downto 24);
              end if;
            when b"010" =>
              if S_AXI_WSTRB(0) = '1' then
                reg_prescaler_reg(7 downto 0) <=
                  S_AXI_WDATA(7 downto 0);
              end if;
              if S_AXI_WSTRB(1) = '1' then
                reg_prescaler_reg(15 downto 8) <=
                  S_AXI_WDATA(15 downto 8);
              end if;
              if S_AXI_WSTRB(2) = '1' then
                reg_prescaler_reg(23 downto 16) <=
                  S_AXI_WDATA(23 downto 16);
              end if;
              if S_AXI_WSTRB(3) = '1' then
                reg_prescaler_reg(31 downto 24) <=
                  S_AXI_WDATA(31 downto 24);
              end if;
            when b"011" =>
              if S_AXI_WSTRB(0) = '1' then
                reg_status_reg(7 downto 0) <=
                  S_AXI_WDATA(7 downto 0);
              end if;
              if S_AXI_WSTRB(1) = '1' then
                reg_status_reg(15 downto 8) <=
                  S_AXI_WDATA(15 downto 8);
              end if;
              if S_AXI_WSTRB(2) = '1' then
                reg_status_reg(23 downto 16) <=
                  S_AXI_WDATA(23 downto 16);
              end if;
              if S_AXI_WSTRB(3) = '1' then
                reg_status_reg(31 downto 24) <=
                  S_AXI_WDATA(31 downto 24);
              end if;
            when b"100" =>
              if S_AXI_WSTRB(0) = '1' then
                reg_cycle_cnt_reg(7 downto 0) <=
                  S_AXI_WDATA(7 downto 0);
              end if;
              if S_AXI_WSTRB(1) = '1' then
                reg_cycle_cnt_reg(15 downto 8) <=
                  S_AXI_WDATA(15 downto 8);
              end if;
              if S_AXI_WSTRB(2) = '1' then
                reg_cycle_cnt_reg(23 downto 16) <=
                  S_AXI_WDATA(23 downto 16);
              end if;
              if S_AXI_WSTRB(3) = '1' then
                reg_cycle_cnt_reg(31 downto 24) <=
                  S_AXI_WDATA(31 downto 24);
              end if;
            when others => null;
          end case;
        end if;
        -- RO capture: DUT output continuously updates shadow register
        reg_status_reg(0) <= pwm_out;
        reg_status_reg(1) <= period_done;
        reg_status_reg(7 downto 4) <= irq_status;
        reg_cycle_cnt_reg(31 downto 0) <= cycle_count;
      end if;
    end if;
  end process p_reg_write;
  -- =========================================================================
  -- Write response channel
  -- =========================================================================
  p_bresp : process(S_AXI_ACLK)
  begin
    if rising_edge(S_AXI_ACLK) then
      if S_AXI_ARESETN = '0' then
        axi_bvalid <= '0';
        axi_bresp  <= "00";
      else
        if axi_awready = '1' and S_AXI_AWVALID = '1' and
           axi_wready  = '1' and S_AXI_WVALID  = '1' and
           axi_bvalid  = '0' then
          axi_bvalid <= '1';
          axi_bresp  <= "00";  -- OKAY
        elsif S_AXI_BREADY = '1' and axi_bvalid = '1' then
          axi_bvalid <= '0';
        end if;
      end if;
    end if;
  end process p_bresp;
  -- =========================================================================
  -- Read address channel: ARREADY
  -- =========================================================================
  p_arready : process(S_AXI_ACLK)
  begin
    if rising_edge(S_AXI_ACLK) then
      if S_AXI_ARESETN = '0' then
        axi_arready <= '0';
        axi_araddr  <= (others => '1');
      else
        if axi_arready = '0' and S_AXI_ARVALID = '1' then
          axi_arready <= '1';
          axi_araddr  <= S_AXI_ARADDR;
        else
          axi_arready <= '0';
        end if;
      end if;
    end if;
  end process p_arready;
  -- =========================================================================
  -- Read data channel: RDATA / RVALID
  --   All non-WO fields read from the shadow register.
  --   RO shadows are updated every cycle from the DUT port in p_reg_write.
  -- =========================================================================
  p_rdata : process(S_AXI_ACLK)
    variable loc_addr : std_logic_vector(OPT_MEM_ADDR_BITS downto 0);
  begin
    if rising_edge(S_AXI_ACLK) then
      if S_AXI_ARESETN = '0' then
        axi_rvalid <= '0';
        axi_rresp  <= "00";
        axi_rdata  <= (others => '0');
      else
        if axi_arready = '1' and S_AXI_ARVALID = '1' and axi_rvalid = '0' then
          axi_rvalid <= '1';
          axi_rresp  <= "00";
          loc_addr := axi_araddr(ADDR_LSB + OPT_MEM_ADDR_BITS downto ADDR_LSB);
          axi_rdata <= (others => '0');
          case loc_addr is
            when b"000" =>
              axi_rdata(0) <= reg_ctrl_reg(0);
              axi_rdata(7 downto 4) <=
                reg_ctrl_reg(7 downto 4);
            when b"001" =>
              axi_rdata(7 downto 0) <=
                reg_duty_reg(7 downto 0);
            when b"010" =>
              axi_rdata(15 downto 0) <=
                reg_prescaler_reg(15 downto 0);
            when b"011" =>
              axi_rdata(0) <= reg_status_reg(0);
              axi_rdata(1) <= reg_status_reg(1);
              axi_rdata(7 downto 4) <=
                reg_status_reg(7 downto 4);
            when b"100" =>
              axi_rdata(31 downto 0) <=
                reg_cycle_cnt_reg(31 downto 0);
            when others => axi_rdata <= (others => '0');
          end case;
        elsif axi_rvalid = '1' and S_AXI_RREADY = '1' then
          axi_rvalid <= '0';
        end if;
      end if;
    end if;
  end process p_rdata;
  -- =========================================================================
  -- Concurrent assignments: shadow registers -> DUT input ports
  --   RW : CPU can write; register value continuously drives the DUT input
  --   WO : same, but reads return '0'
  -- =========================================================================
  enable <= reg_ctrl_reg(0);
  irq_mask <= reg_ctrl_reg(7 downto 4);
  duty_cycle <= reg_duty_reg(7 downto 0);
  prescaler <= reg_prescaler_reg(15 downto 0);

end architecture rtl;
