-- =============================================================================
-- AUTO-GENERATED by axi_wrapper -- DO NOT EDIT MANUALLY
-- Top wrapper: connects pwm_controller with AXI4-Lite register interface
-- =============================================================================
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity pwm_controller_axi is
  generic (
    -- AXI interface parameters
    C_S_AXI_DATA_WIDTH : integer := 32;
    C_S_AXI_ADDR_WIDTH : integer := 5;
    -- DUT generics (forwarded to pwm_controller)
    CLK_FREQ_HZ : integer := 100_000_000;
    PWM_BITS : integer := 8
  );
  port (
    -- AXI4-Lite clock and reset
    S_AXI_ACLK    : in  std_logic;
    S_AXI_ARESETN : in  std_logic;
    -- Write address channel
    S_AXI_AWADDR  : in  std_logic_vector(C_S_AXI_ADDR_WIDTH-1 downto 0);
    S_AXI_AWPROT  : in  std_logic_vector(2 downto 0);
    S_AXI_AWVALID : in  std_logic;
    S_AXI_AWREADY : out std_logic;
    -- Write data channel
    S_AXI_WDATA   : in  std_logic_vector(C_S_AXI_DATA_WIDTH-1 downto 0);
    S_AXI_WSTRB   : in  std_logic_vector((C_S_AXI_DATA_WIDTH/8)-1 downto 0);
    S_AXI_WVALID  : in  std_logic;
    S_AXI_WREADY  : out std_logic;
    -- Write response channel
    S_AXI_BRESP   : out std_logic_vector(1 downto 0);
    S_AXI_BVALID  : out std_logic;
    S_AXI_BREADY  : in  std_logic;
    -- Read address channel
    S_AXI_ARADDR  : in  std_logic_vector(C_S_AXI_ADDR_WIDTH-1 downto 0);
    S_AXI_ARPROT  : in  std_logic_vector(2 downto 0);
    S_AXI_ARVALID : in  std_logic;
    S_AXI_ARREADY : out std_logic;
    -- Read data channel
    S_AXI_RDATA   : out std_logic_vector(C_S_AXI_DATA_WIDTH-1 downto 0);
    S_AXI_RRESP   : out std_logic_vector(1 downto 0);
    S_AXI_RVALID  : out std_logic;
    S_AXI_RREADY  : in  std_logic;
    -- Unmapped DUT ports (passed through directly)
    clk                           : in    std_logic;
    rst_n                         : in    std_logic
  );
end entity pwm_controller_axi;

architecture structural of pwm_controller_axi is
  -- -------------------------------------------------------------------------
  -- Component declaration: axi_lite_if
  -- -------------------------------------------------------------------------
  component axi_lite_if is
    generic (
      C_S_AXI_DATA_WIDTH : integer := 32;
      C_S_AXI_ADDR_WIDTH : integer := 5
    );
    port (
      S_AXI_ACLK    : in  std_logic;
      S_AXI_ARESETN : in  std_logic;
      S_AXI_AWADDR  : in  std_logic_vector(C_S_AXI_ADDR_WIDTH-1 downto 0);
      S_AXI_AWPROT  : in  std_logic_vector(2 downto 0);
      S_AXI_AWVALID : in  std_logic;
      S_AXI_AWREADY : out std_logic;
      S_AXI_WDATA   : in  std_logic_vector(C_S_AXI_DATA_WIDTH-1 downto 0);
      S_AXI_WSTRB   : in  std_logic_vector((C_S_AXI_DATA_WIDTH/8)-1 downto 0);
      S_AXI_WVALID  : in  std_logic;
      S_AXI_WREADY  : out std_logic;
      S_AXI_BRESP   : out std_logic_vector(1 downto 0);
      S_AXI_BVALID  : out std_logic;
      S_AXI_BREADY  : in  std_logic;
      S_AXI_ARADDR  : in  std_logic_vector(C_S_AXI_ADDR_WIDTH-1 downto 0);
      S_AXI_ARPROT  : in  std_logic_vector(2 downto 0);
      S_AXI_ARVALID : in  std_logic;
      S_AXI_ARREADY : out std_logic;
      S_AXI_RDATA   : out std_logic_vector(C_S_AXI_DATA_WIDTH-1 downto 0);
      S_AXI_RRESP   : out std_logic_vector(1 downto 0);
      S_AXI_RVALID  : out std_logic;
      S_AXI_RREADY  : in  std_logic;
      enable                        : out std_logic;
      irq_mask                      : out std_logic_vector(3 downto 0);
      duty_cycle                    : out std_logic_vector(7 downto 0);
      prescaler                     : out std_logic_vector(15 downto 0);
      pwm_out                       : in  std_logic;
      period_done                   : in  std_logic;
      irq_status                    : in  std_logic_vector(3 downto 0);
      cycle_count                   : in  std_logic_vector(31 downto 0);
      dummy_unused  : in std_logic := '0'
    );
  end component axi_lite_if;
  -- -------------------------------------------------------------------------
  -- Component declaration: pwm_controller
  -- -------------------------------------------------------------------------
  component pwm_controller is
    generic (
      CLK_FREQ_HZ : integer := 100_000_000;
      PWM_BITS : integer := 8
    );
    port (
      clk                           : in    std_logic;
      rst_n                         : in    std_logic;
      enable                        : in    std_logic;
      duty_cycle                    : in    std_logic_vector(7 downto 0);
      prescaler                     : in    std_logic_vector(15 downto 0);
      irq_mask                      : in    std_logic_vector(3 downto 0);
      pwm_out                       : out   std_logic;
      period_done                   : out   std_logic;
      irq_status                    : out   std_logic_vector(3 downto 0);
      cycle_count                   : out   std_logic_vector(31 downto 0)
    );
  end component pwm_controller;
  -- -------------------------------------------------------------------------
  -- Internal signals between axi_lite_if and pwm_controller
  -- -------------------------------------------------------------------------
  signal sig_enable                      : std_logic;
  signal sig_irq_mask                    : std_logic_vector(3 downto 0);
  signal sig_duty_cycle                  : std_logic_vector(7 downto 0);
  signal sig_prescaler                   : std_logic_vector(15 downto 0);
  signal sig_pwm_out                     : std_logic;
  signal sig_period_done                 : std_logic;
  signal sig_irq_status                  : std_logic_vector(3 downto 0);
  signal sig_cycle_count                 : std_logic_vector(31 downto 0);

begin
  -- =========================================================================
  -- AXI4-Lite register interface instance
  -- =========================================================================
  axi_lite_if_inst : axi_lite_if
    generic map (
      C_S_AXI_DATA_WIDTH => C_S_AXI_DATA_WIDTH,
      C_S_AXI_ADDR_WIDTH => C_S_AXI_ADDR_WIDTH
    )
    port map (
      S_AXI_ACLK    => S_AXI_ACLK,
      S_AXI_ARESETN => S_AXI_ARESETN,
      S_AXI_AWADDR  => S_AXI_AWADDR,
      S_AXI_AWPROT  => S_AXI_AWPROT,
      S_AXI_AWVALID => S_AXI_AWVALID,
      S_AXI_AWREADY => S_AXI_AWREADY,
      S_AXI_WDATA   => S_AXI_WDATA,
      S_AXI_WSTRB   => S_AXI_WSTRB,
      S_AXI_WVALID  => S_AXI_WVALID,
      S_AXI_WREADY  => S_AXI_WREADY,
      S_AXI_BRESP   => S_AXI_BRESP,
      S_AXI_BVALID  => S_AXI_BVALID,
      S_AXI_BREADY  => S_AXI_BREADY,
      S_AXI_ARADDR  => S_AXI_ARADDR,
      S_AXI_ARPROT  => S_AXI_ARPROT,
      S_AXI_ARVALID => S_AXI_ARVALID,
      S_AXI_ARREADY => S_AXI_ARREADY,
      S_AXI_RDATA   => S_AXI_RDATA,
      S_AXI_RRESP   => S_AXI_RRESP,
      S_AXI_RVALID  => S_AXI_RVALID,
      S_AXI_RREADY  => S_AXI_RREADY,
      enable                         => sig_enable,
      irq_mask                       => sig_irq_mask,
      duty_cycle                     => sig_duty_cycle,
      prescaler                      => sig_prescaler,
      pwm_out                        => sig_pwm_out,
      period_done                    => sig_period_done,
      irq_status                     => sig_irq_status,
      cycle_count                    => sig_cycle_count,
      dummy_unused  => '0'
    );
  -- =========================================================================
  -- DUT instance: pwm_controller
  -- =========================================================================
  pwm_controller_inst : pwm_controller
    generic map (
      CLK_FREQ_HZ => CLK_FREQ_HZ,
      PWM_BITS => PWM_BITS
    )
    port map (
      clk                            => clk,
      rst_n                          => rst_n,
      enable                         => sig_enable,
      duty_cycle                     => sig_duty_cycle,
      prescaler                      => sig_prescaler,
      irq_mask                       => sig_irq_mask,
      pwm_out                        => sig_pwm_out,
      period_done                    => sig_period_done,
      irq_status                     => sig_irq_status,
      cycle_count                    => sig_cycle_count
    );

end architecture structural;
