-- =============================================================================
-- AUTO-GENERATED by axi_wrapper -- DO NOT EDIT MANUALLY
-- Top wrapper: connects logic_gate_controller with AXI4-Lite register interface
-- =============================================================================
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity logic_gate_controller_axi is
  generic (
    -- AXI interface parameters
    C_S_AXI_DATA_WIDTH : integer := 32;
    C_S_AXI_ADDR_WIDTH : integer := 5;
    -- DUT generics (forwarded to logic_gate_controller)
    LOGIC_GATES_N : integer := 16;
    PATTERN_WIDTH : integer := 4
  );
  port (
    -- AXI4-Lite clock and reset
    S_AXI_ACLK    : in  std_logic;
    S_AXI_ARESETN : in  std_logic;
    -- Write address channel
    S_AXI_AWADDR  : in  std_logic_vector(C_S_AXI_ADDR_WIDTH-1 downto 0);
    S_AXI_AWPROT  : in  std_logic_vector(2 downto 0);
    S_AXI_AWVALID : in  std_logic;
    S_AXI_AWREADY : out std_logic;
    -- Write data channel
    S_AXI_WDATA   : in  std_logic_vector(C_S_AXI_DATA_WIDTH-1 downto 0);
    S_AXI_WSTRB   : in  std_logic_vector((C_S_AXI_DATA_WIDTH/8)-1 downto 0);
    S_AXI_WVALID  : in  std_logic;
    S_AXI_WREADY  : out std_logic;
    -- Write response channel
    S_AXI_BRESP   : out std_logic_vector(1 downto 0);
    S_AXI_BVALID  : out std_logic;
    S_AXI_BREADY  : in  std_logic;
    -- Read address channel
    S_AXI_ARADDR  : in  std_logic_vector(C_S_AXI_ADDR_WIDTH-1 downto 0);
    S_AXI_ARPROT  : in  std_logic_vector(2 downto 0);
    S_AXI_ARVALID : in  std_logic;
    S_AXI_ARREADY : out std_logic;
    -- Read data channel
    S_AXI_RDATA   : out std_logic_vector(C_S_AXI_DATA_WIDTH-1 downto 0);
    S_AXI_RRESP   : out std_logic_vector(1 downto 0);
    S_AXI_RVALID  : out std_logic;
    S_AXI_RREADY  : in  std_logic;
    -- Unmapped DUT ports (passed through directly)
    clk                           : in    std_logic;
    rst_n                         : in    std_logic;
    input_a                       : in    std_logic_vector(31 downto 0);
    error_detected_o              : out   std_logic;
    logic_gate_in_a               : out   std_logic_vector(LOGIC_GATES_N - 1 downto 0);
    logic_gate_in_b               : out   std_logic_vector(LOGIC_GATES_N - 1 downto 0);
    logic_gate_output             : in    std_logic_vector(LOGIC_GATES_N - 1 downto 0)
  );
end entity logic_gate_controller_axi;

architecture structural of logic_gate_controller_axi is
  -- -------------------------------------------------------------------------
  -- Component declaration: axi_lite_if
  -- -------------------------------------------------------------------------
  component axi_lite_if is
    generic (
      C_S_AXI_DATA_WIDTH : integer := 32;
      C_S_AXI_ADDR_WIDTH : integer := 5
    );
    port (
      S_AXI_ACLK    : in  std_logic;
      S_AXI_ARESETN : in  std_logic;
      S_AXI_AWADDR  : in  std_logic_vector(C_S_AXI_ADDR_WIDTH-1 downto 0);
      S_AXI_AWPROT  : in  std_logic_vector(2 downto 0);
      S_AXI_AWVALID : in  std_logic;
      S_AXI_AWREADY : out std_logic;
      S_AXI_WDATA   : in  std_logic_vector(C_S_AXI_DATA_WIDTH-1 downto 0);
      S_AXI_WSTRB   : in  std_logic_vector((C_S_AXI_DATA_WIDTH/8)-1 downto 0);
      S_AXI_WVALID  : in  std_logic;
      S_AXI_WREADY  : out std_logic;
      S_AXI_BRESP   : out std_logic_vector(1 downto 0);
      S_AXI_BVALID  : out std_logic;
      S_AXI_BREADY  : in  std_logic;
      S_AXI_ARADDR  : in  std_logic_vector(C_S_AXI_ADDR_WIDTH-1 downto 0);
      S_AXI_ARPROT  : in  std_logic_vector(2 downto 0);
      S_AXI_ARVALID : in  std_logic;
      S_AXI_ARREADY : out std_logic;
      S_AXI_RDATA   : out std_logic_vector(C_S_AXI_DATA_WIDTH-1 downto 0);
      S_AXI_RRESP   : out std_logic_vector(1 downto 0);
      S_AXI_RVALID  : out std_logic;
      S_AXI_RREADY  : in  std_logic;
      test_en                       : out std_logic;
      errors_rst                    : out std_logic;
      input_b                       : out std_logic_vector(31 downto 0);
      errors                        : in  std_logic_vector(31 downto 0);
      truth_table                   : out std_logic_vector(31 downto 0);
      errors_select                 : out std_logic_vector(31 downto 0);
      read_latency                  : out std_logic_vector(31 downto 0);
      dummy_unused  : in std_logic := '0'
    );
  end component axi_lite_if;
  -- -------------------------------------------------------------------------
  -- Component declaration: logic_gate_controller
  -- -------------------------------------------------------------------------
  component logic_gate_controller is
    generic (
      LOGIC_GATES_N : integer := 16;
      PATTERN_WIDTH : integer := 4
    );
    port (
      clk                           : in    std_logic;
      rst_n                         : in    std_logic;
      test_en                       : in    std_logic;
      input_a                       : in    std_logic_vector(31 downto 0);
      input_b                       : in    std_logic_vector(31 downto 0);
      truth_table                   : in    std_logic_vector(31 downto 0);
      errors_select                 : in    std_logic_vector(31 downto 0);
      errors                        : out   std_logic_vector(31 downto 0);
      errors_rst                    : in    std_logic;
      read_latency                  : in    std_logic_vector(31 downto 0);
      error_detected_o              : out   std_logic;
      logic_gate_in_a               : out   std_logic_vector(LOGIC_GATES_N - 1 downto 0);
      logic_gate_in_b               : out   std_logic_vector(LOGIC_GATES_N - 1 downto 0);
      logic_gate_output             : in    std_logic_vector(LOGIC_GATES_N - 1 downto 0)
    );
  end component logic_gate_controller;
  -- -------------------------------------------------------------------------
  -- Internal signals between axi_lite_if and logic_gate_controller
  -- -------------------------------------------------------------------------
  signal sig_test_en                     : std_logic;
  signal sig_errors_rst                  : std_logic;
  signal sig_input_b                     : std_logic_vector(31 downto 0);
  signal sig_errors                      : std_logic_vector(31 downto 0);
  signal sig_truth_table                 : std_logic_vector(31 downto 0);
  signal sig_errors_select               : std_logic_vector(31 downto 0);
  signal sig_read_latency                : std_logic_vector(31 downto 0);

begin
  -- =========================================================================
  -- AXI4-Lite register interface instance
  -- =========================================================================
  axi_lite_if_inst : axi_lite_if
    generic map (
      C_S_AXI_DATA_WIDTH => C_S_AXI_DATA_WIDTH,
      C_S_AXI_ADDR_WIDTH => C_S_AXI_ADDR_WIDTH
    )
    port map (
      S_AXI_ACLK    => S_AXI_ACLK,
      S_AXI_ARESETN => S_AXI_ARESETN,
      S_AXI_AWADDR  => S_AXI_AWADDR,
      S_AXI_AWPROT  => S_AXI_AWPROT,
      S_AXI_AWVALID => S_AXI_AWVALID,
      S_AXI_AWREADY => S_AXI_AWREADY,
      S_AXI_WDATA   => S_AXI_WDATA,
      S_AXI_WSTRB   => S_AXI_WSTRB,
      S_AXI_WVALID  => S_AXI_WVALID,
      S_AXI_WREADY  => S_AXI_WREADY,
      S_AXI_BRESP   => S_AXI_BRESP,
      S_AXI_BVALID  => S_AXI_BVALID,
      S_AXI_BREADY  => S_AXI_BREADY,
      S_AXI_ARADDR  => S_AXI_ARADDR,
      S_AXI_ARPROT  => S_AXI_ARPROT,
      S_AXI_ARVALID => S_AXI_ARVALID,
      S_AXI_ARREADY => S_AXI_ARREADY,
      S_AXI_RDATA   => S_AXI_RDATA,
      S_AXI_RRESP   => S_AXI_RRESP,
      S_AXI_RVALID  => S_AXI_RVALID,
      S_AXI_RREADY  => S_AXI_RREADY,
      test_en                        => sig_test_en,
      errors_rst                     => sig_errors_rst,
      input_b                        => sig_input_b,
      errors                         => sig_errors,
      truth_table                    => sig_truth_table,
      errors_select                  => sig_errors_select,
      read_latency                   => sig_read_latency,
      dummy_unused  => '0'
    );
  -- =========================================================================
  -- DUT instance: logic_gate_controller
  -- =========================================================================
  logic_gate_controller_inst : logic_gate_controller
    generic map (
      LOGIC_GATES_N => LOGIC_GATES_N,
      PATTERN_WIDTH => PATTERN_WIDTH
    )
    port map (
      clk                            => clk,
      rst_n                          => rst_n,
      test_en                        => sig_test_en,
      input_a                        => input_a,
      input_b                        => sig_input_b,
      truth_table                    => sig_truth_table,
      errors_select                  => sig_errors_select,
      errors                         => sig_errors,
      errors_rst                     => sig_errors_rst,
      read_latency                   => sig_read_latency,
      error_detected_o               => error_detected_o,
      logic_gate_in_a                => logic_gate_in_a,
      logic_gate_in_b                => logic_gate_in_b,
      logic_gate_output              => logic_gate_output
    );

end architecture structural;
